### ISSUE TITLE
Please consider using spaces

### ISSUE THREAD

**Issue by sayem314** [mholt/caddy-ratelimit#1]
At least on the readme. This hurts every brain cell.

![image](https://user-images.githubusercontent.com/14138401/112948604-16c49c00-915a-11eb-9ae7-8ca3a1d096b7.png)

> Two spaces is the way to go!

**Comment by mholt** [comment]
I agree the tabs are rendered far too wide on GitHub. I wish they would switch to 2-wide or 4-wide tabs.

However, my editor auto formats JSON snippets, so it'll be a bother to disable that for this file. I'll try next time I get around to it, but every time I edit it, the editor will probably put the tabs back.

**Comment by francislavoie** [comment]
I suggest using https://github.com/sindresorhus/refined-github which renders tabs as 2 spaces.

**Comment by mholt** [comment]
Update: GitHub now lets you specify your own preferred tab width, yay! (Problem solved)
