### ISSUE TITLE
Possibility to add exceptions/whitelist

### ISSUE THREAD

**Issue by AnTheMaker** [mholt/caddy-ratelimit#15]
Hi there!
First of all: thank you for creating Caddy and this plugin, I love both! Great work!!
Here's my questions:
Is it possible to add an exception for specific IP addresses or subnets to bypass the rate-limit?
Maybe this is already possible with how Caddy works, but I haven't been able to figure it out yet.
For example, I'd love to whitelist my internal network, so my own servers don't run into the ratelimit.
My rate limit configuration currently looks like this:
```
rate_limit {
        zone my_zone {
                key    {remote_host}
                events 10
                window 20s
        }
}
```
Thank you very much!
I appreciate any help!

**Comment by francislavoie** [comment]
Yes - use a `not` + `remote_ip` matcher with `rate_limit` to make it not apply for the IP addresses or ranges you want to permit.

**Comment by mholt** [comment]
Was just about to say that!

In other words:

```
@not_excepted not remote_ip 1.2.3.4
rate_limit @not_excepted ...
```

**Comment by AnTheMaker** [comment]
Oh, that's way easier than I expected. Will try it later today!
Thank you so much to both of you!!

**Comment by ananthdevulapalli** [comment]
Hi all
It would also be great if I could white-list a specific IP address where the rate limit should not work for this IP address
below is the syntax 

     rate_limit {
     distributed
     rate_limit @not_excepted 192.168.0.1
     zone dynamic_example {
                key    {remote_host}
                events 500
                window 1m
        }
}

correct me the syntax is wrong

**Comment by francislavoie** [comment]
See Matt's comment; declare a named matcher which matches requests by remote IP, then apply it to the `rate_limit` directive. See how matchers work: https://caddyserver.com/docs/caddyfile/matchers#syntax
