### ISSUE TITLE
Rate limit based on path, but doesn't work

### ISSUE THREAD

**Issue by Likenttt** [mholt/caddy-ratelimit#18]
Hi, I wanna do rate limit based on the host + path, but the config below didn't work.
```
{
        order rate_limit before basicauth
}

https://example.com {
        rate_limit {
                distributed
                zone dynamic_example {
                        key {remote_host}
                        events 1000
                        window 60s
                }
                zone pair_api {
                       match {
                               path /api/auth/pair
                       }
                       key {remote_host}/api/auth/pair
                       events 1
                       window 10s
                }
        }
}
```

```
zone pair_api {
       match {
               path /api/auth/pair
       }
       key {remote_host}/api/auth/pair
       events 1
       window 10s
}
```
I followed this instruction
> Each zone may optionally filter the requests it applies to by specifying [request matchers](https://caddyserver.com/docs/modules/http#servers/routes/match).

Anything wrong about this snippet? Thanks in advance

**Comment by mholt** [comment]
Note that matchers in zones via the Caddyfile are not yet implemented:

> **PLANNED:**
> - Ability to define matchers in zones with Caddyfile

You'll have to use the JSON config for that for now. Sorry!

**Comment by Likenttt** [comment]
> Note that matchers in zones via the Caddyfile are not yet implemented:
> 
> > **PLANNED:**
> > 
> > * Ability to define matchers in zones with Caddyfile
> 
> You'll have to use the JSON config for that for now. Sorry! It's something I can prioritize if a company would like to sponsor that.
Sorry, I didn't know the term a matcher in zones. Now I got it.

How to buy you a beer or coffee

**Comment by mholt** [comment]
(No worries, I didn't specify very clearly.)

Ha, I don't drink either of those actually :upside_down_face: I appreciate the thought, maybe see if your company would like to sponsor the Caddy project -- we're aiming to grow our community and maintainers!

Thank you :slightly_smiling_face:

**Comment by tasiotas** [comment]
also looking forward to this feature 😍

**Comment by muety** [comment]
Would love to have this!

**Comment by mholt** [comment]
Will reopen since it looks like people want _Caddyfile config_ specifically -- I can prioritize this with a sufficient sponsorship.
