### ISSUE TITLE
It really just doesn't work with Caddy 2.6.4

### ISSUE THREAD

**Issue by mhmdksh** [mholt/caddy-ratelimit#21]
To replicate the issue, I tried the below:

Building my Caddy docker image with the below config:

`Dockerfile:`

```
FROM caddy:2.6.4-alpine AS builder

RUN apk add --no-cache git go && \
    GO111MODULE=on go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest && \
    /root/go/bin/xcaddy build \
        --with github.com/mholt/caddy-ratelimit

FROM caddy:2.6.4-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

Using this `Caddyfile` config:

```
{
	order rate_limit before basicauth
}
http://example.com {
    root * /usr/share/caddy
    rate_limit {
        zone mydynamiczone {
            key    {remote_host}
            events 10
            window 1m
        }
        distributed {
            write_interval 5s
            read_interval 5s
        }
        sweep_interval 1m
    }
}
```

Error: Error during parsing: unrecognized directive: rate_limit

Am I missing anything?? Why is it still not recognized as a directive? Is the latest Caddy Images 2.6.4 supported?

**Comment by mhmdksh** [comment]
@mholt FYI

**Comment by mohammed90** [comment]
Are you sure you're running the correct Docker image? Can you share your process to build, deploy, and run the image?

**Comment by mhmdksh** [comment]
@mohammed90 I shared the Dockerfile that I am building in my comment above. I am building on top of `caddy:2.6.4-alpine` image. I also tried the normal image `caddy:2.6.4`

Is there any documentation on which specific image I should be using?

**Comment by mohammed90** [comment]
> @mohammed90 I shared the Dockerfile that I am building in my comment above. I am building on top of `caddy:2.6.4-alpine` image. I also tried the normal image `caddy:2.6.4`
> 
> Is there any documentation on which specific image I should be using?

The Dockerfile you provided is the definition of the image. The error message you're seeing indicates you aren't running the image you think you're running. So we need to know how you're building it and how you're running it. Basically, we need to know what commands you've executed after writing the Dockerfile.

**Comment by mhmdksh** [comment]
Thanks for the clarification @mohammed90 

I am using this with a docker-compose setup that builds the Dockerfile and start the service. You can find the full details in my repository here: https://github.com/mhmdksh/caddy-experiment

**Comment by francislavoie** [comment]
You didn't specify the output of xcaddy build so it builds to your current PWD and not to /usr/bin/caddy, so you're copying the default Caddy binary onto itself.

See the docs on Docker Hub, we have a `builder` image variant which ships with Go and xcaddy. Use that instead, it's configured correctly for building with plugins.

**Comment by mhmdksh** [comment]
> You didn't specify the output of xcaddy build so it builds to your current PWD and not to /usr/bin/caddy, so you're copying the default Caddy binary onto itself.
> 
> See the docs on Docker Hub, we have a `builder` image variant which ships with Go and xcaddy. Use that instead, it's configured correctly for building with plugins.

@francislavoie 

Thanks so much for pointing that out, getting into many builds can definitely seem tricky sometimes. Building the module (And the module) worked just fine when I used the `builder` [image](https://github.com/caddyserver/caddy-docker/blob/8a3bab4e266cc4e32c57d757890bbc1b6ff54e1d/2.6/builder/Dockerfile) variant.

Thanks again for the active community spirit you guys have :)
