### ISSUE TITLE
Distributed Retry-After

### ISSUE THREAD

**Issue by plunkettscott** [mholt/caddy-ratelimit#22]
I almost filed a bug report because after trying a few storage modules with distributed rate limits, the `Retry-After` was always being set to 0. I dug into the code and see that this is actually [a static value](https://github.com/mholt/caddy-ratelimit/blob/2dc0d586f0b87e983757c403bc0929ddeb84a537/distributed.go#L198).

Any ideas on how we can finish implementing `Retry-After` for distributed zones? I understand this probably isn't a very high priority feature for you, however, I'd be willing to work on it if there's some form of calculation you have in mind for the value.

**Comment by mholt** [comment]
Hi, good question! It's been a while since I've looked at this code so I'll need to make some time and get in the headspace to figure out a solution. (If a company needs this sooner rather than later, we can arrange a sponsorship and I'll prioritize it.) Otherwise, I'd welcome a proposal and/or PR!

**Comment by mholt** [comment]
@plunkettscott Done in #34 thanks to a contribution :)
