### ISSUE TITLE
Log rate limited IPs

### ISSUE THREAD

**Issue by jakanaka** [mholt/caddy-ratelimit#37]
I want to log which IP's are rate limited with date and stuff. Is it already possible now?

**Comment by mholt** [comment]
Good q -- we don't currently emit logs when a rate limit has been reached.

What would you like to have, specifically?

cf. https://github.com/mholt/caddy-ratelimit/blob/89a7fece9addf6881169642d0b8a18e79d58e179/handler.go#L200

**Comment by mholt** [comment]
Added in 3d68475 -- let me know if that doesn't work for you!

**Comment by francislavoie** [comment]
Does this only log the first time the limit is hit, or on every request after? Could be quite noisy and add pressure if they're hitting fast, no?

**Comment by mholt** [comment]
Log sampling can be configured to tame eccentric logs. But yeah we don't keep any state as to whether it's a first hit or not.
