### ISSUE TITLE
Different storage for rate_limit

### ISSUE THREAD

**Issue by odarriba** [mholt/caddy-ratelimit#39]
Hello,

Is it possible to store rate_limit related information in a different storage than the default Caddy's one?

If you for example use NFS to synchronize TLS certificates and so on, it would be nice to be able to set another storage (like Redis?) for rate_limit, as the delay in NFS reads/writes can affect the performance of the rate limiter.

Thanks in advance

**Comment by mohammed90** [comment]
> Is it possible to store rate_limit related information in a different storage than the default Caddy's one?

Yes. See in [the JSON config](https://caddyserver.com/docs/modules/http.handlers.rate_limit#github.com/mholt/caddy-ratelimit), the handler configuration can take `storage` as one of the parameters.

The same thing for [the Caddyfile config](https://github.com/mholt/caddy-ratelimit/blob/master/caddyfile.go#L38-L53).
