### ISSUE TITLE
can MatcherSetsRaw be populated using caddyfile?

### ISSUE THREAD

**Issue by elee1766** [mholt/caddy-ratelimit#41]
hi

i was looking through https://github.com/mholt/caddy-ratelimit/blob/master/caddyfile.go and saw that there was no place where MatcherSetsRaw is populated in caddyfile parsing.

am i correct to believe that matchers currently can be set via json config only? 

i was looking for an example of a module that parsed matchers in caddyfile, i guess this isnt the one?

**Comment by mohammed90** [comment]
> am i correct to believe that matchers currently can be set via json config only?

No, that's not accurate. The matcher handling is managed by the `RegisterHandlerDirective`, which is used in this line:

https://github.com/mholt/caddy-ratelimit/blob/a2b31878ccd2f470e01f76e4673c0cebbc314b8a/caddyfile.go#L28

**Comment by elee1766** [comment]
> > am i correct to believe that matchers currently can be set via json config only?
> 
> No, that's not accurate. The matcher handling is managed by the `RegisterHandlerDirective`, which is used in this line:
> 
> https://github.com/mholt/caddy-ratelimit/blob/a2b31878ccd2f470e01f76e4673c0cebbc314b8a/caddyfile.go#L28

ah i see. that makes sense. i see now it is defined here: https://github.com/caddyserver/caddy/blob/master/caddyconfig/httpcaddyfile/directives.go#L113-L131

thanks!
