### ISSUE TITLE
Build fail with official caddy builder dockerfile

### ISSUE THREAD

**Issue by sebMathieu** [mholt/caddy-ratelimit#48]
Hi ! 

Since the commit of yesterday the build based on the official docker builder fails. The error is quite explicit : 

`github.com/mholt/caddy-ratelimit@v0.0.0-20240513211706-2d18cd2c76cc requires go >= 1.22.0 (running go 1.21.10; GOTOOLCHAIN=local)`

It would be nice to make version tags in the git repository. Currently it is not easy to fallback to the previous version.
Here is a dockerfile for complete reproduction : 

```docker
FROM caddy:2-builder AS builder

RUN xcaddy build \
    --with github.com/greenpau/caddy-security \
    --with github.com/mholt/caddy-ratelimit

FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

PS : It's a nice occasion to say that using Caddy and all this plugins is really great and thank all the maintainers and developers.

**Comment by sebMathieu** [comment]
As a temporary solution, one can use the image instead.

```dockerfile
FROM caddy:2.8.0-beta.2-builder AS builder
```

**Comment by Matasx** [comment]
Hello, same issue here as of today. Upvoting. (The temporary solution is also working for me).

**Comment by brotbert** [comment]
@sebMathieu @Matasx Don't forget to set the environment variable `CADDY_VERSION=latest` or replace `xcaddy build` with `xcaddy build latest` if you don't want to run the beta version `v2.8.0-beta.2`.

**Comment by mholt** [comment]
Should be fixed on master now
