### ISSUE TITLE
Waiting for first release

### ISSUE THREAD

**Issue by sowinski** [mholt/caddy-ratelimit#51]
Hi,

when do you plan to release the first version of caddy-ratelimit? Or do you not plan to introduce releases at all?

Regards

**Comment by mholt** [comment]
Haven't really had requests for it. Releases for Caddy plugins isn't always needed because you can build from any commit so easily with `xcaddy` or our download page. Why would you like a release?

**Comment by sowinski** [comment]
Because if gives the user a feeling of safety. I would suggest that a release is more stable/used/tested as a continues repository.

**Comment by francislavoie** [comment]
That's just your perception though. That's not the truth. There's no practical difference between there being releases or not.

But having releases is one extra step we'd _have_ to take every time if we start doing it. If we have one release, we need to continue making releases forever, adding a bit of work to maintaining this repo, because of how Go modules determine which git ref to use.

**Comment by mholt** [comment]
Yep, a release only means something if it means something. If we just tag a release but don't do anything else differently, then we're not really helping anything.

**Comment by Wint3rmute** [comment]
@mholt, @sowinski here's a different argument for introducing tagged releases for `caddy-ratelimit`, which may (or may not) convince you :)

Support for compiling Caddy with plugins [has been added to NixOS last week](https://github.com/NixOS/nixpkgs/pull/358586). NixOS' specification requires users to provide a tag name or commit ID for each plugin they want to bundle with their build of Caddy, see examples in the link above.

Now whether you are interested about this NixOS-specific use case is up to you. I understand if you only want to support `xcaddy`-based builds. For NixOS users, it would be far more readable to provide a plugin tag in their system specification than having to use a commit ID.

**Comment by mholt** [comment]
I guess I could do a pre-1.0 tag; there's not much actively being developed on this module currently.
