### ISSUE TITLE
Configuration for caddy-docker-proxy

### ISSUE THREAD

**Issue by sowinski** [mholt/caddy-ratelimit#53]
Hi,

is it possible to run caddy-ratelimit with caddy-docker-proxy.
I currently tried this approach with no success: [](https://github.com/lucaslorentz/caddy-docker-proxy/issues/612#issuecomment-2150392848)

I want a global rate limit for all my docker containers. So my idea was it add it to my Caddyfile with no success.
Did anyone has success to use it with caddy-docker-proxy?

**Comment by francislavoie** [comment]
Already answered here https://github.com/lucaslorentz/caddy-docker-proxy/issues/612#issuecomment-2150551863
