### ISSUE TITLE
Use `RegisterDirectiveOrder` for `rate_limit` before `basic_auth`

### ISSUE THREAD

**Issue by steffenbusch** [mholt/caddy-ratelimit#58]
I believe it would be a nice improvement if the **Caddy HTTP Rate Limit Module** leveraged the new `RegisterDirectiveOrder` feature from Caddy v2.8 (caddyserver/caddy#5865).

```diff
func init() {
	httpcaddyfile.RegisterHandlerDirective("rate_limit", parseCaddyfile)
+	httpcaddyfile.RegisterDirectiveOrder("rate_limit", "before", "basic_auth")
}
```

I would open a PR, but I am unsure if upgrading the `go.mod` requirements from `github.com/caddyserver/caddy/v2 v2.7.6` to `v2.8.4`, along with all the other necessary updates after running `go mod tidy`, is acceptable for you and if it might break something for other users. I simply don't know enough about Go / Caddy module dependencies to assess this.

**Comment by francislavoie** [comment]
The minimum version required to use that is v2.8.0 so we can put that in the `go.mod`, though up to .4 is just bugfix releases, people shouldn't be building with an earlier patch at this point.
