### ISSUE TITLE
Does this module support the leaky bucket algorithm (as a queue)?

### ISSUE THREAD

**Issue by x-yuri** [mholt/caddy-ratelimit#67]
From what I can see, the answer is no. If so, is this in the plans? It seems like it might be useful to keep a number of requests in a queue to handle them later. Basically I'm referring to the `burst` parameter of `nginx`.

**Comment by mholt** [comment]
It's a sliding window, so you can have bursts.

If you want to enqueue things, you are looking for a _throttle_, not a rate limiter. Rate limiters just decide yes/no for something at a given moment. Throttles are associated with queues.
